// app/metadata.ts
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "openai-gpt-3",
  description: "generated by openai-gpt-3",
  icons: {
    icon: "/favicon.ico",
  }
};